sudo: false
language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
env:
- DB=MYSQL CORE_RELEASE=3.2
matrix:
  include:
  - php: 5.6
    env: DB=MYSQL CORE_RELEASE=3.1
  - php: 5.6
    env: DB=PGSQL CORE_RELEASE=3.2
  - php: 5.6
    env: DB=MYSQL CORE_RELEASE=3.2 PDO=1
  allow_failures:
  - php: 7.0

before_install:
- openssl aes-256-cbc -K $encrypted_cbb750526dea_key -iv $encrypted_cbb750526dea_iv
  -in docs/travisci_rsa.enc -out docs/travisci_rsa -d
- chmod 0600 docs/travisci_rsa
- cp docs/travisci_rsa ~/.ssh/id_rsa

before_script:
- export PATH=~/.composer/vendor/bin:$PATH
- composer self-update || true
- git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
- php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
- cd ~/builds/ss
- composer install

script:
- vendor/bin/phpunit silverstripe-rest-api/tests/

after_success:
- composer global require phpdocumentor/phpdocumentor
- chmod a+x silverstripe-rest-api/docs/publish-docs
- silverstripe-rest-api/docs/publish-docs
