---
Name: rest_api
After:
  - 'framework/*'
  - 'cms/*'
---
Injector:
  Authenticator:
    class: Ntb\RestAPI\TokenAuth
  ApiMemberAuthenticator:
    class: MemberAuthenticator
  SessionValidator:
    class: Ntb\RestAPI\SessionValidator
  PermissionChecks:
    class: Ntb\RestAPI\SilverstripePermission
TokenAuth:
  DevToken: foobarbaz
JwtAuth:
  Key: LoremIpsum
  HashAlgorithm: sha256
  Issuer: "rest.ntb.dev"
  ExpireTime: 1209600
  DevToken: foobarbaz
HttpAuth:
  Realm: RestApiAuth
BaseRestController:
  CORSOrigin: '*'
  CORSMethods: 'GET, PUT, POST, DELETE, OPTIONS'
  CORSMaxAge: '1000'
  CORSAllowHeaders: 'Content-Type, Authorization, X-Requested-With'
  Owner: Member
SessionValidator:
  email_name: email
  password_name: password
NestedResourceRestController:
  root_resource_id_field: ID